# syntax=docker/dockerfile:1

FROM python:3.10.14-bullseye

RUN pip3 install pyinstaller

COPY requirements.txt requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

VOLUME /src/
WORKDIR /src/

ENTRYPOINT [ "/usr/local/bin/pyinstaller" ]
